README.md
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/manage_dict.py
resources/home/dnanexus/run_workflows/utils/utils.py
src/eggd_conductor.sh

Handle filtering of job outputs by pattern(s) where gathering up all the output fields of multiple jobs, and providing a subset of these as input for a downstream app/workflow (i.e. taking all output BAM/VCF files from multiple app jobs and filtering just files for NA12878)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/3)

Handle job output filtering

---

resources/home/dnanexus/run_workflows/utils/dx_requests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/13)

fix bug on finding DNAnexus project check

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/manage_dict.py
resources/home/dnanexus/run_workflows/utils/utils.py

- Add sorting of fastqs before adding to input dict to keep sentieon app happy where L002 is passed before L001
- Add check to copy `Stats.json` from bcl2fastq output to the analysis project from argparse NameSpace instead of project context (which is the project eggd_conductor is running in)
- Fix duplicate test name
- Minor pep8 things and tidying up
```
$ python3 -m pytest -v resources/home/dnanexus/run_workflows/tests/
====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_conductor
plugins: Faker-14.0.0, …
```

Add sorting of fastqs, tidying up

---

resources/home/dnanexus/run_workflows/utils/dx_requests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/15)

fix setting clone directory of stats.json to project root

---

README.md
example/example_populated_config.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py

- handle `extra_args` as a key in the config to pass to each dx run call to specify additional arguments such as for priority
- specify to only read from first column of samplesheet to parse out sample list to handle variable numbers of columns
Extra args defined in config correctly makes job run as high priority:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/16)

Handle extra args to set priority and instance type etc

---

src/eggd_conductor.sh

- Fixes #22
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/23)

fix assay config variable

---

README.md
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py

- adds optional field to assay config file to provide an app ID for demultiplexing to override one in app config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/25)

Demultiplex app override

---

README.md
dxapp.json
src/eggd_conductor.sh

- Adds functionality to suppress automated running of app by tagging of the sentinel file for the run
- Fixes #11 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/27)

Suppress auotmation

---

src/eggd_conductor.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/33)

remove redundant unpacking

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/utils.py
src/eggd_conductor.sh

- Make Yujin happy by switching emoji and text for notification when not able to find a Jira ticket for a run
- Other minor tweaks to notification formatting for consistency
- Fixes #39 
Examples:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/46)

Improve Slack notifications

---

README.md

Improved documentation
- Fixes #36 
- Fixes #37
- Fixes #38
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/48)

v1.2.0 readme

---

src/eggd_conductor.sh

- Revert back to uploading samplesheet if parsed from run data and setting env variable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/49)

Fix samplesheet passing

---

src/eggd_conductor.sh

Adding project name to success notification on launching all jobs:
Example:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/50)

add project name to success notification

---

README.md
resources/home/dnanexus/run_workflows/utils/dx_requests.py

- Fix passing samplesheet as input to demultiplexing when specified as input and parsed from sentinel file
- Add examples to readme of using `extra_args` key for overriding app run spec
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/51)

v1.2.0 fix pulling samplesheet

---

README.md
example/example_populated_config.json

Minor readme changes and update example populated assay config file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/52)

v1.2.0 readme update

---

README.md
dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
src/eggd_conductor.sh

Add assay config file used as output to the app for better auditing of analysis
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/55)

v1.2.0 config output

---

README.md

tiny doc updates
Closes #69 
Closes #74
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/77)

v1.3.0 update ze readme

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
src/eggd_conductor.sh

- add tag to eggd_conductor whilst held jobs are running:
- add check for project permissions correctly set for team token to ensure jobs can be launched in the given project (i.e. checking if the project has been shared with the org, this fixes #86 . 
- Example of error raised if project has not been shared with org: ![image](https://github.com/eastgenomics/eggd_conductor/assets/45037268/58482ceb-b32c-4c73-9108-23b766189110)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/94)

v1.4.0 - minor features

---

dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py
src/eggd_conductor.sh

- add in yet another optional input, this time to be able to exclude specific samples from per sample steps (i.e reports workflows)
- comes with bonus unit tests to show it works
- example job with valid samples specified to exclude: https://platform.dnanexus.com/panx/projects/GfK06Pj412V7Qbfb2zJqPZ8y/monitor/job/GfKYK58412VBBJ4X5kQzFy7b
- launched jobs:
- example job with invalid sample name specified: https://platform.dnanexus.com/panx/projects/GfK06Pj412V7Qbfb2zJqPZ8y/monitor/job/GfKYjBj412V3jpfqGj52Gy2G
- Slack alert sent: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/96)

v1.4.0 exclude samples

---

README.md

- update readme for clarity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/97)

v1.4.0 - update readme

---

README.md

- update details on job-based references for inputs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/104)

v1.4.0 - readme update

---

resources/home/dnanexus/run_workflows/utils/manage_dict.py

- removes duplication of destination as it is already set here: https://github.com/eastgenomics/eggd_conductor/blob/03c73de2266b6ea25eea48c9b3f1dc646bf8482c/resources/home/dnanexus/run_workflows/run_workflows.py#L538
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/106)

remove duplicated output directory

---

resources/home/dnanexus/run_workflows/utils/manage_dict.py

- switch order of additional files input
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/107)

v1.4.0 - fix order of additional files

---

resources/home/dnanexus/run_workflows/tests/test_manage_dict.py

- fix borked test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/108)

v1.4.0 - fix unit test

---

dxapp.json
src/eggd_conductor.sh

- improves the suppress automation alert message sent on sentinel record being tagged to add in commands
- fixes #109 
- example: https://binfx.slack.com/archives/C03LFU1AAQL/p1720109020736389
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/119)

IN-693 v1.5.0 update suppress alert

---

src/eggd_conductor.sh

- add extra missing line break to suppress notification
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/120)

IN-693 v1.5.0 - update error message

---

README.md
dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_utils.py
resources/home/dnanexus/run_workflows/utils/utils.py
src/eggd_conductor.sh

- merging of signed off v1.5.0 release into main
- related testing: https://cuhbioinformatics.atlassian.net/browse/IN-693
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/121)

v1.5.0 release -> main

---

dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/dx_utils.py
resources/home/dnanexus/run_workflows/utils/utils.py

- Starting DXBuilder conversion
- Start adapting `run_workflows`
- Move functions around to `dx_utils`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)

In 711 handle multiple configs - Part 1

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/manage_dict.py

- Change some whitespace that i don't like
- Limit usage of args as a parameter everywhere
- Build jobs per sample and per run method for the DXBuilder
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/128)

In 711 handle multiple configs - Part 4

---

dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/dx_utils.py
resources/home/dnanexus/run_workflows/utils/manage_dict.py
resources/home/dnanexus/run_workflows/utils/request_objects.py
src/eggd_conductor.sh

- Rename DX parameters and appropriate changes in the bash code
- Fix a lot of errors
- Fix using the config assay code rather than the actual config dict
- FIx some imports
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/130)

In 711 handle multiple configs - Part 6

---

dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
src/eggd_conductor.sh

- Mixed run assays works now \o/:
- https://platform.dnanexus.com/panx/projects/GqVBq2Q4JbJ7zZXBGfZ7vKXx/monitor/analysis/GqVFy0Q4JbJ2JQJgYZX0pfz6
- https://platform.dnanexus.com/panx/projects/GqVF7J04xy50qYJ35F9585yP/monitor/analysis/GqVFy384xy57VJZqpGPBz77b
- Assay config arg at runtime is now a array:file
- Fix some shellcheck things
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/131)

In 711 handle multiple configs - Part 7

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_requests.py
resources/home/dnanexus/run_workflows/utils/request_objects.py
src/eggd_conductor.sh

- Ticket comment handling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132)

In 711 handle multiple configs - Part 8 (untested)

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_assay_handler.py
resources/home/dnanexus/run_workflows/tests/test_dx_utils.py
resources/home/dnanexus/run_workflows/utils/AssayHandler.py
resources/home/dnanexus/run_workflows/utils/WebClasses.py
resources/home/dnanexus/run_workflows/utils/dx_utils.py
resources/home/dnanexus/run_workflows/utils/utils.py

- Fix some bugs discovered during unittesting
- First part of unittests for Assay Handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/135)

In 711 handle multiple configs - Part 11 - Part 1 of Unittests of new code

---

resources/home/dnanexus/run_workflows/tests/test_assay_handler.py
resources/home/dnanexus/run_workflows/utils/utils.py

- Tests for `call_job`
- Fix warning for `select_instance_types`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/139)

Part 15: More tests

---

resources/home/dnanexus/run_workflows/tests/test_assay_handler.py
resources/home/dnanexus/run_workflows/tests/test_demultiplexing.py
resources/home/dnanexus/run_workflows/utils/demultiplexing.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/140)

Part 16: Test for demultiplexing functions

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_assay_handler.py
resources/home/dnanexus/run_workflows/utils/AssayHandler.py
resources/home/dnanexus/run_workflows/utils/utils.py
src/eggd_conductor.sh

- massive try/except block in order to keep the job starts from failing if one of the assays has issues
- remove the total job file
- add the number of jobs started to the analysis project log file
- move job reuse checking to `utils.py`
- fix job termination bug in bash
- adjust slack summary message of jobs started
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/142)

Part 18: In 713 handle cancelling of jobs depending of which config is concerned

---

README.md
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/AssayHandler.py
resources/home/dnanexus/run_workflows/utils/WebClasses.py
resources/home/dnanexus/run_workflows/utils/demultiplexing.py
resources/home/dnanexus/run_workflows/utils/dx_utils.py
resources/home/dnanexus/run_workflows/utils/manage_dict.py
resources/home/dnanexus/run_workflows/utils/utils.py
src/eggd_conductor.sh

- Updated readme
- Updated docstrings
- Added whitespaces
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/144)

Part 20: In 813 pass to fix docstrings and change readme

---

resources/home/dnanexus/run_workflows/run_workflows.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/145)

Part 20.1: Forgot to add file id output

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/utils/dx_utils.py
src/eggd_conductor.sh

- Fix `_testing_clean_up` use
- Remove `job_id.log` file usage
- Fix bug where ticket errors triggered errors in the bash section of the code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/147)

Part 21.1: Fix more issues

---

resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_assay_handler.py
resources/home/dnanexus/run_workflows/utils/AssayHandler.py

- Resolves #150
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/151)

Part 21.4: Protected status for production runs

---

resources/home/dnanexus/run_workflows/run_workflows.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/152)

Part 21.5: Fix URL in JIRA comment

---

README.md
dxapp.json
resources/home/dnanexus/run_workflows/run_workflows.py
resources/home/dnanexus/run_workflows/tests/test_utils.py
resources/home/dnanexus/run_workflows/utils/AssayHandler.py
resources/home/dnanexus/run_workflows/utils/manage_dict.py
resources/home/dnanexus/run_workflows/utils/utils.py
src/eggd_conductor.sh

- Remove run info xml usage. Resolves #153 
- Fix bug where if a tso500 reports workflow job was not started due to missing output, there was no line indicating this as expected in the job summary file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/154)

Part 21.6: Last one i swear
