eastgenomics/eggd_conductor

- README.md
- resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- src/eggd_conductor.sh
Adds extra optional input of samplesheet as `INPUT-SAMPLESHEET` for apps (currently required by [update_runfolders](https://github.com/eastgenomics/eggd_update_runfolders)).
Example conductor job: https://platform.dnanexus.com/projects/GB3jx784Bv40j3Zx4P5vvbzQ/monitor/job/GJ2b8XQ4Bv4F4b95139ggvX9
Dias multi job with samplesheet parsed: https://platform.dnanexus.com/projects/GB3jx784Bv40j3Zx4P5vvbzQ/monitor/analysis/GJ2b9kQ4Bv45Y56p8yfGz8Zy
```
jethro@jethro-T490:~/Projects/eggd_conductor$ python3 -m pytest -v --disable-pytest-warnings resources/home/dnanexus/run_workflows/tests/ 
==================================================================== test session starts ====================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, …
```
> Handle samplesheet input

- .gitignore
- README.md
- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- src/eggd_conductor.sh
Add another input for the config file of `INPUT-UPLOAD_TARS` to allow passing upload tars associated to sentinel file as an input.
This will allow for launching TSO500 app.
Other minor changes:
- made matching of samples to configs case insensitive to account for `egg` vs `EGG`
- fix bug in URL of Slack alert sent on fail from bash script
Example conductor job: https://platform.dnanexus.com/projects/GB3jx784Bv40j3Zx4P5vvbzQ/monitor/job/GJ49q384Bv49VXxz4FkfXP8Q
Example TSO500 job launched : https://platform.dnanexus.com/projects/GB3jx784Bv40j3Zx4P5vvbzQ/monitor/job/GJ49qP04Bv43x33499qkpg2x
Tests:
```
$ python3 -m pytest -v --disable-pytest-warnings resources/home/dnanexus/run_workflows/tests/ 
==================================================================== test session starts …
```
> Handle upload tars as input

- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- src/eggd_conductor.sh
Fix when samplesheet specified with `-iSAMPLESHEET` it wasn't correctly parsed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/18)
> Fix parsing samplesheet from env

- dxapp.json
- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- src/eggd_conductor.sh
Adds all launched job IDs as an output to the automation job to be picked up for monitoring
Example job: https://platform.dnanexus.com/projects/GJq6Bb04v59bqJyjGKXgkbkY/monitor/job/GKX66904v59bpVZq8K20pb5x
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/30)
> add launched job IDs as app output

- dxapp.json
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
Switch to getting sentinel record ID from argument instead of environment to be more robust
Fixes https://github.com/eastgenomics/eggd_conductor/issues/42
Test job: https://platform.dnanexus.com/projects/GQ0xPyj49GgpqvxvQb6kF08y/monitor/job/GQ0xYB849Ggb8PY91K3kP1px
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/43)
> Fix adding upload tars as input

- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
Fixes #44 
Example job: https://platform.dnanexus.com/projects/GQ0xPyj49GgpqvxvQb6kF08y/monitor/job/GQ0y4G849GgXBKz0gVK47VxG
From job logs showing matching `EGG6` assay code to `egg6` in samplenames:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/45)
> make matching assay codes to samplenames case insensitive

- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- src/eggd_conductor.sh
- better handling of failed demultiplexing jobs - fixes #40
- actually use given samplesheet for demultiplexing
Example notification for failed job:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/47)
> demultiplexing fixes

- README.md
- dxapp.json
- resources/home/dnanexus/run_workflows/run_workflows.py
- src/eggd_conductor.sh
##Summary
Change to make default behaviour to launch analysis jobs in same project as conductor is running, this is to improve safety and stop accidentally running jobs in 002 projects.
Fixes #62 
- New input `CREATE_PROJECT` (default: `false`) to control if to automatically create an analysis project
- No project specified (i.e. launch in same project): https://platform.dnanexus.com/projects/GVbfzG0409P6527X7PGXpV98/monitor/job/GVbg888409P0y5K5P55G9vK7 
- DNAnexus project specified to use: https://platform.dnanexus.com/projects/GVbfzG0409P6527X7PGXpV98/monitor/job/GVbgBJ0409PFXF4pyF355fz1 
- `CREATE_PROJECT=true` (i.e. automatically create an analysis project as will be done in production): https://platform.dnanexus.com/projects/GVbfzG0409P6527X7PGXpV98/monitor/job/GVbgJV8409P4202Vx6g7bfJ …
> v1.3.0 - change default behaviour for project selection

- resources/home/dnanexus/run_workflows/run_workflows.py
Fix for being able to use `--samples` to provide a comma separated string of samples on which to run jobs, useful for specifying a normal sample and control when running test jobs
Fixes #66 
Example of fix in job logs:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/75)
> unbork --samples input

- dxapp.json
Remove old VALIDATE_SAMPLESHEET input, no longer used and removed from code previously but not from `dxapp.json`
Fixes #65
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/76)
> more housekeeping

- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/tests/test_run_workflows.py
Fix bug in sample matching to assay configs where previously was matching on the code and not version, this is switched to correctly select from the version from the values, then select the corresponding assay code for the given version
Added a bonus unit test to check its now working as expected
Fixes [#80 a real life bug](https://github.com/eastgenomics/eggd_conductor/issues/80)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/81)
> Fix ze bug

- src/eggd_conductor.sh
Adds `launchedBy` user to initial start notification
Closes #79 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/84)
> v1.3.0 add user

- dxapp.json
- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/utils/dx_log.py
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- src/eggd_conductor.sh
- pass through output provided to the app with `--destination` if specified to be the top level output of launched jobs
- Fixes #89 
- for workflows, set the common path of constituent apps to be the folder output (functionally doesn't change anything as `stage_folders` controls the app output, but now displays better in web UI)
- Fixes #71 
- make the assay config file used just be a string output instead of file
- example job with destination set: https://platform.dnanexus.com/panx/projects/GbvyYZj4zQV7xXvj49XBXF4V/monitor/job/Gbvzj6j4zQV6Z22fv474vp3p
- launched workflow: https://platform.dnanexus.com/panx/projects/GbvyYZj4zQV7xXvj49XBXF4V/monitor/analysis/GbvzkqQ4zQV4PxF97V6Y2b4j
- example job without destination set: https://platform.dnanexus.com/panx/projects/GbvyYZj4zQV7xXvj49XBXF4V/ …
> v1.4.0 - set destination

- .github/workflows/pytest.yml
- requirements.txt
- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/tests/__init__.py
- resources/home/dnanexus/run_workflows/tests/settings.py
- resources/home/dnanexus/run_workflows/tests/test_dx_requests.py
- resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
- resources/home/dnanexus/run_workflows/tests/test_run_workflows.py
- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- resources/home/dnanexus/run_workflows/utils/utils.py
Add in functionality for specifically handling of parsing eggd_tso500/2.0.0 output -> TSO500 reports workflow for automating running all of Helios pipeline
- New functions:
- `DXManage.get_job_output_details()` - used to get full describe output of a given jobs output files
- `DXManage.wait_on_done()` - refactor of code from `main()` added in #92 to separate function for easier unit testing
- `ManageDict.populate_tso500_reports_workflow()` - main logic for parsing of eggd_tso500 output into per sample reports workflows
- unit tests added for new functions
- added GitHub action to run unit tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/93)
> v1.4.0 - handle TSO500 reports workflow

- README.md
- dxapp.json
- resources/home/dnanexus/run_workflows/run_workflows.py
- src/eggd_conductor.sh
- adds additional optional input `-iJOB_REUSE` to allow for patching in previously run jobs to reuse output from
- main use case for this is for running reports workflows for TSO500 and decoupling this from always having to rerun the eggd_tso500 app
- example job specifying an eggd_tso500 job ID to reuse from: https://platform.dnanexus.com/panx/projects/GfK06Pj412V7Qbfb2zJqPZ8y/monitor/job/GfKXQg0412V9P7Y9KxFxFfKB
- from above job logs: 
- launched downstream jobs: 
- example job without reuse specified: https://platform.dnanexus.com/panx/projects/GfK06Pj412V7Qbfb2zJqPZ8y/monitor/job/GfKXbV8412V6KF3VqqxzgBvZ
- launched job: 
- example of catching error where invalid JSON string provided to `-iJOB_REUSE`: https://platform.dnanexus.com/panx/projects/GfK06Pj412V7Qbfb2zJqPZ8y/monitor/job/GfKY2 …
> v1.4.0 - add job_reuse input

- resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- src/eggd_conductor.sh
- fix for querying TSO500 jobs with a missing output field (i.e. all DNA samples => expected no RNA outputs)
- handle spaces in `-iJOB_REUSE` input
- specify key sorting of fastqs and additional unit test to `TestAddFastqs`
- fixes #88 
- example launching all DNA samples:
- example of space in `-iJOB_REUSE` input:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/99)
> v1.4.0 - fix tso500 reports launch + fix for #88

- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- resources/home/dnanexus/run_workflows/utils/utils.py
- src/eggd_conductor.sh
- add in run ID to all error Slack alerts
- fixes #100 
- ![image](https://github.com/eastgenomics/eggd_conductor/assets/45037268/74ac90b1-5fc8-4522-ad92-c2639f9229b6)
- when running in test mode, make launched jobs dependent on parent eggd_conductor job so they don't actually run before terminating
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/101)
> v1.4.0 - improve slack alert

- resources/home/dnanexus/run_workflows/utils/dx_requests.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- fix for when specifying `-iJOB_REUSE` for a prior run eggd_tso500 job if that job was a clone it broke reusing the job ID
- if a job is re-run the name will be in the following format when described:
```[16:24:03] - {
⠀⠀"eggd_tso500 (re-run)": "job-GgB5qj84xjk46B02JGb4ZjJp",
⠀⠀"multi_fastqc_v1.1.0": "job-GgBJ48j4zQV2QB5PVGvgZX29"
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/103)
> v1.4.0 - fix for job reuse on re-run jobs

- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/tests/test_manage_dict.py
- resources/home/dnanexus/run_workflows/utils/manage_dict.py
- fix to add destination (if specified with `--destination`) to the parent output directory passed through to `INPUT-parent_out_dir` (i.e. for MultiQC)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/105)
> v1.4.0 - fix destination

- README.md
- dxapp.json
- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/tests/test_utils.py
- resources/home/dnanexus/run_workflows/utils/utils.py
- src/eggd_conductor.sh
Changes to handle excluding pancan samples from being processed through TSO500 pipeline where we have mixed assay sequencing runs
- add additional function `utils.subset_samplesheet_samples`  
- takes the list of samples from the samplesheet and a regex pattern defined in the assay config to filter down the sample list, this will exclude samples not matching the pattern from having per sample analyses launched
- add unit tests for the above new function
- bonus new line for `printf` in `eggd_conductor.sh`
- fix example demultiplex config in readme
- add `panx` to final Slack notification URL
- fixes #112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/118)
> IN-693 v1.5.0 subset samplesheet

- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/utils/utils.py
- Have prettier prints for the samples to be processed, samples/patterns to exclude and the final assay -> sample dict
- Fix issue where the exclusion of samples wasn't working because i wasn't specifying which set of samples to exclude samples from
- Additional print for when the number of configs using `-iassay_config` and the number of assay handlers kept are not equal (discrepancy can happen when 2 configs are specified and all samples are excluded from an assay -> 1 assay handler is kept)
- Fix horrifying slack message for ticketing errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/146)
> Part 21: Fix issues

- resources/home/dnanexus/run_workflows/utils/dx_utils.py
- src/eggd_conductor.sh
- Conductor will fail if fastqs are provided but no `run_id`
- Prettify config messages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/148)
> Part 21.2: Add restriction when providing fastqs

- README.md
- dxapp.json
- resources/home/dnanexus/run_workflows/run_workflows.py
- resources/home/dnanexus/run_workflows/tests/test_demultiplexing.py
- resources/home/dnanexus/run_workflows/utils/demultiplexing.py
- resources/home/dnanexus/run_workflows/utils/utils.py
- src/eggd_conductor.sh
- Improve printing
- Set the run id variable in the environment for use in the error message
- Fix parsing if the first element in the `exclude_samples` starts with a hyphen
- Stop sending an error message if it occurred in the running job bit and an error message has already been sent
- Remove `mismatch_allowance`
- Fix issue where the demultiplex config was not passed
- Fix parsing of project name when uploading job summary file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_conductor/149)
> Part 21.3: Fix some bugs
